from procsim.front_end.instructions.add import Add
from procsim.front_end.instructions.addi import AddI
from procsim.front_end.instructions.sub import Sub
from procsim.front_end.instructions.subi import SubI
from procsim.front_end.instructions.mul import Mul
from procsim.front_end.instructions.muli import MulI
from procsim.front_end.instructions.load import Load
from procsim.front_end.instructions.store import Store
from procsim.front_end.instructions.jump import Jump
from procsim.front_end.instructions.blth import Blth
